version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      github-actions:
        applies-to: version-updates
        patterns: ['*']
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      npm-dependencies:
        applies-to: version-updates
        patterns: ['*']
  - package-ecosystem: cargo
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      cargo-dependencies:
        applies-to: version-updates
        patterns: ['*']
  - package-ecosystem: pip
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
    groups:
      python-dependencies:
        applies-to: version-updates
        patterns: ['*']
