blockExoticSubdeps: false

overrides:
  '@openzeppelin/contracts': 4.9.6
  '@openzeppelin/contracts-4.7.3': 'npm:@openzeppelin/contracts@4.9.6'
  '@openzeppelin/contracts-upgradeable': 4.9.6
  'axios@<1.0.0': 0.33.0
  'axios@>=1.0.0 <1.16.0': 1.18.1
  lodash: 4.18.1
  protobufjs: 7.6.5
  serialize-javascript: 7.0.5
  tmp: 0.2.7
  undici: 6.27.0
  ws: 8.21.0

allowBuilds:
  '@arbitrum/nitro-contracts': true
  '@axelar-network/axelarjs-sdk': true
  '@imtbl/contracts': true
  keccak: true
  node-hid: true
  protobufjs: true
  'seaport@https://codeload.github.com/immutable/seaport/tar.gz/ae061dc008105dd8d05937df9ad9a676f878cbf9': true
  secp256k1: true
  usb: true

peerDependencyRules:
  allowedVersions:
    ethers: ^6.13.2
    hardhat-deploy: ^0.12.4
    hardhat-gas-reporter: ^2.2.1
