name: Code Foundry

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: 0xPlayerOne/code-foundry/.github/workflows/ci.yml@v0.31.13
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: v0.31.13
      runner: ubuntu-latest
    secrets: inherit
