name: Validate, build, and test on every push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'yarn'
      - name: Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Hardhat compile
        uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Run Prettier
        uses: borales/actions-yarn@v5
        with:
          cmd: format
      - name: Lint TS Scripts
        uses: borales/actions-yarn@v5
        with:
          cmd: lint:ts
      - name: Lint Solidity files
        uses: borales/actions-yarn@v5
        with:
          cmd: lint:sol
      - name: Check TypeScript
        uses: borales/actions-yarn@v5
        with:
          cmd: type-check
      - name: Run Hardhat tests
        uses: borales/actions-yarn@v5
        with:
          cmd: test
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
      - name: Check Solidity coverage
        uses: borales/actions-yarn@v5
        with:
          cmd: coverage
      - name: Test contract deployment
        continue-on-error: false
        run: npx hardhat run --network hardhat src/scripts/deploy_test.ts
