name: Validate, build, and test on every push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Hardhat compile
        run: pnpm build
      - name: Run Prettier
        run: pnpm format
      - name: Lint TS Scripts
        run: pnpm lint:ts
      - name: Lint Solidity files
        run: pnpm lint:sol
      - name: Check TypeScript
        run: pnpm type-check
      - name: Run Hardhat tests
        run: pnpm test
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
      - name: Check Solidity coverage
        run: pnpm coverage
      - name: Test contract deployment
        continue-on-error: false
        run: pnpm hardhat run --network hardhat src/scripts/deploy_test.ts
