name: Validate, build, and test on every push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.14"
      - name: Install dependencies
        run: bun install
      - name: Hardhat compile
        run: bun build
      - name: Run Prettier
        run: bun format
      - name: Lint TS Scripts
        run: bun lint:ts
      - name: Lint Solidity files
        run: bun lint:sol
      - name: Check TypeScript
        run: bun type-check
      - name: Run Hardhat tests
        run: bun test
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
      - name: Check Solidity coverage
        run: bun coverage
      - name: Test contract deployment
        continue-on-error: false
        run: bun hardhat run --network hardhat src/scripts/deploy_test.ts
