name: Code Foundry

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'chore/*'
      - 'refactor/*'
      - 'docs/*'
      - 'style/*'
      - 'test/*'

permissions:
  contents: read
  pull-requests: write

jobs:
  draft-pr:
    name: Draft PR
    uses: 0xPlayerOne/code-foundry/.github/workflows/draft-pr.yml@v0.31.3
    with:
      runner: ubuntu-slim
    secrets: inherit
