name: Code Foundry

on:
  push:
    branches: [staging]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  release-pr:
    if: >-
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.head_ref, 'release-please--branches--main')
    name: Release PR
    uses: 0xPlayerOne/code-foundry/.github/workflows/release-pr.yml@v0.34.4
    with:
      runner: ubuntu-slim
    secrets: inherit
