name: Code Foundry

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    uses: 0xPlayerOne/code-foundry/.github/workflows/test.yml@v0.31.2
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: v0.31.2
      runner: ubuntu-latest
      unit-runner: ubuntu-slim
    secrets: inherit
